#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Feb 05 23:39:59 ICT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=MakeUp-UltraFast-9.4b.zip
enableShaders=true
